### ISSUE TITLE
The lambda doesn't work with postgres >= 11.6

### ISSUE THREAD

**Issue by felipelerena** [jameshy/pgdump-aws-lambda#28]
```
Invoke Error 	{"errorType":"Error","errorMessage":"pg_dump process failed: pg_dump: server version: 12.5; pg_dump version: 11.6\npg_dump: aborting because of server version mismatch\n","stack":["Error: pg_dump process failed: pg_dump: server version: 12.5; pg_dump version: 11.6","pg_dump: aborting because of server version mismatch","","    at ChildProcess.<anonymous> (/var/task/lib/pgdump.js:54:21)","    at ChildProcess.emit (events.js:315:20)","    at ChildProcess.EventEmitter.emit (domain.js:467:12)","    at maybeClose (internal/child_process.js:1048:16)","    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)"]}
```

**Comment by jameshy** [comment]
Hi Felipe!

Thanks for reporting, i'll update the binary soon.

**Comment by 592da** [comment]
Same for version 13.2 :(

**Comment by NanoCode012** [comment]
Hello, I'm sorry to unearth an old thread, but I also got this issue with Supabase postgresql .  I was wondering if the binaries can be updated again?

```
Error: pg_dump process failed: pg_dump: error: server version: 14.1
```

**Comment by jameshy** [comment]
Hey @NanoCode012.

Yes please make a PR with the new binaries!

I'm not sure about lambda layers.. I'm not working at all with AWS these days..

**Comment by barthuygen** [comment]
Same for version >= 16 :(
