### ISSUE TITLE
Access Denied when running the lambda

### ISSUE THREAD

**Issue by christiaanwesterbeek** [jameshy/pgdump-aws-lambda#41]
> START RequestId: ab6ee9a3-2ce8-460e-94c6-18a13c4f15c4 Version: $LATEST
> 2022-06-03T17:08:18.467Z	ab6ee9a3-2ce8-460e-94c6-18a13c4f15c4	ERROR	AccessDenied: Access Denied
>     at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:710:35)
>     at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>     at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)
>     at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
>     at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
>     at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)

**Comment by christiaanwesterbeek** [comment]
Solved by these steps.

1. In AWS Lambda in your Lambda function, go to the Configuration tab
2. Click on the role name that executes the lambda
3. That brings you to IAM
4. In the Permissions tab, expand the policy that was already there.
5. Edit that policy
6. Choose tab JSON
7. Change the policy like so and save it.

Now you can retry running your Lambda.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/465989/171915910-1c220ebb-5ade-465e-b681-ac9b49ea7f6e.png">

```
{
    "Effect": "Allow",
    "Action": [
        "s3:GetObject",
        "s3:PutObject"
    ],
    "Resource": "arn:aws:s3:::*"
}
```

reference: https://stackoverflow.com/questions/35589641/aws-lambda-function-getting-access-denied-when-getobject-from-s3
