### ISSUE TITLE
spawn EACCES

### ISSUE THREAD

**Issue by Tarang** [jameshy/pgdump-aws-lambda#8]
I'm using the binary set at https://github.com/jameshy/pgdump-aws-lambda/releases/download/v1.1.4/pgdump-aws-lambda.zip with node 6.10

As far as I can tell I have full permissions for role im using to execute.

The error:
```
{ Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at spawnPgDump (/var/task/lib/pgdump.js:17:12)
    at Promise (/var/task/lib/pgdump.js:28:25)
    at pgdumpWrapper (/var/task/lib/pgdump.js:23:12)
    at module.exports (/var/task/lib/handler.js:29:27) code: 'EACCES', errno: 'EACCES', syscall: 'spawn' }
```

The pg_dump file doesn't have the correct permissions in the zip file

**Comment by jameshy** [comment]
Thanks for the report.

I have fixed this in [v1.1.6](https://github.com/jameshy/pgdump-aws-lambda/releases/tag/v1.1.6)
